import { GeistSans } from "geist/font/sans";
import "./globals.css";
import Footer from "@/components/global/Footer";
import Nav from "@/components/global/Navbar";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Analytics } from "@vercel/analytics/react";

export const metadata = {
  title: "Stacks",
  description: "A catalog of web dev stacks generated by users.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body className="bg-background text-foreground">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <main className="min-h-screen flex flex-col gap-5 items-center">
            <Nav />
            <div className="flex-1 max-w-4xl px-5 md:px-0">{children}</div>
            <Footer />
          </main>
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
