import { Inter } from "next/font/google"

import "./globals.css"

import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"

import Footer from "@/components/global/Footer"
import Nav from "@/components/global/Navbar"
import { Providers } from "@/components/global/Providers"

// export const runtime = "edge"
// export const preferredRegion = "home"
export const dynamic = "force-dynamic"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
	title: "Stacks",
	description: "A catalog of web dev stacks generated by users.",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en" className={inter.className}>
			<body className="bg-background text-foreground">
				<Providers
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<main className="flex min-h-screen flex-col items-center gap-5">
						<Nav />
						<div className="w-full max-w-4xl flex-1 px-5 lg:px-0">
							{children}
						</div>
						<Footer />
					</main>
				</Providers>
				<Analytics />
				<SpeedInsights />
			</body>
		</html>
	)
}
